-- ------ --
-- Tables --
-- ------ --
-- MenuScreens
TableMenuScreens = {
  '0   ',
  '1  Menu',
  '2  Ability',
  '3  Job',
  '4  Equip',
  '5  Status',
  '6  Shop',
  '7  Item',
  '8  Magic',
  '9  Config',
  '10 Dropped Items',
  '11 Save Game',
  '12 Load Game',
  '13 Name',
  '14 ??'
}
TableMenuScreens[86] = 'Game Start'

-- Statuses (Full Names)
TableStatusCurable = {
  'Dark',
  'Zombie',
  'Poison',
  'Float',
  'Mini',
  'Toad',
  'Petrify',
  'Dead'
}

TableStatusTemporary = {
  'Image (x1)',
  'Image (x2)',
  'Mute',
  'Berserk',
  'Charm',
  'Paralyze',
  'Sleep',
  'Aging'
}

TableStatusDispellable = {
  'Regen',
  'Invul',
  'Slow',
  'Haste',
  'Stop',
  'Shell',
  'Protect',
  'Reflect'
}

TableStatusPermanent = {
  'Hidden',
  'Near Death',
  'Singing',
  'Hp Leak',
  'Countdown',
  'Controlled',
  'False Image',
  'Erased'
}

-- Statuses (Abbr)
TableStatusC = {
  'Drk',
  'Zom',
  'Poi',
  'Flo',
  'Mini',
  'Toad',
  'Ston',
  'Dead'
}
-- Temp Status (Abbr)
TableStatusT = {
  'Im1',
  'Im2',
  'Mute',
  'Ber',
  'Charm',
  'Par',
  'Sleep',
  'Age'
}
-- Dispel Status (Abbr)
TableStatusD = {
  'Reg',
  'Inv',
  'Slo',
  'Has',
  'Stop',
  'Shl',
  'Pro',
  'Ref'
}
-- Permanant Status (Abbr)
TableStatusP = {
  'Hide',
  'Crit',
  'Sing',
  'Slip',
  'Count',
  'Controlled',
  'False Image',
  'Erased'
}

-- Elements
TableElement = {
  'Fire', -- 1
  'Ice', -- 2
  'Lit', -- 4
  'Pois', -- 8
  'Holy', -- 16
  'Earth', -- 32
  'Wind', -- 64
  'Water' -- 128
}
-- Attack Types
TableAttackType = {
  'Blue',
  'White',
  'Black',
  'Dimen',
  'Summon',
  'Song',
  'Aerial',
  'Physical'
}
-- Creature Types
TableCreature = {
  'Undead',
  'Archaetoad',
  'Creature',
  'Avis',
  'Dragon',
  'Heavy',
  'Desert',
  'Human'
}
-- Attack Formula
TableAttackFormula = {
  'No effect',
  'Monster Attack',
  'Monster Specialty',
  'Magic SW -Type 1',
  'Magic SW -Type 2',
  'Magic SW -Type 3',
  'Offensive Magic',
  'Fractional HP based damage',
  'Pierce Magic defense',
  'Random Damage',
  'Physical magic',
  'Level based damage (+ Status?)',
  'HP leak',
  'HP drain',
  'MP drain',
  'HP to critical',
  'Restore HP (Magic)',
  'Restore full HP (Magic)',
  'Status 0 infliction',
  'Status 1 infliction',
  'Status 2 infliction',
  'Toggle Status',
  'Speed Status(Exclusive)',
  'Instant death',
  'Instant destroy',
  'Status removal',
  'Resurrection(fractional)',
  'Whispering Wind',
  'Element attribute change',
  'View stats',
  'Drag',
  'Void',
  'End battle',
  'Reset battle',
  'Double commands',
  'Earth Wall',
  'Restore HP (Item)',
  'Restore MP (Item)',
  'Restore HP / MP',
  'Inflict status, ignore immunity',
  'Fixed damage, ignore defense',
  'Countdown destroy',
  'Max HP based damage + HP leak',
  'Current user HP based damage',
  'Random effect',
  'Ground attacks',
  "Reaper's Sword",
  '?',
  'Unarmed',
  'Swords',
  'Knives',
  'Spears',
  'Axes , Staves',
  'Bows (Status effect)',
  'Bows (Elemental)',
  'Katanas',
  'Whips',
  'Bells',
  'Long reach axes',
  'Rods',
  'Rune weapons',
  'Reduce HP to critical + Status',
  'Reduce HP to critical or HP Leak',
  'Zombie Breath',
  'Change Row',
  '?',
  'HP and status restored',
  '!Steal (command)',
  'Escape (enemy)',
  '!Throw (command)',
  '!GilToss (command)',
  '!Tame (command)',
  '!Catch (command)',
  'Flirt',
  '!Dance(Command)',
  'Lv5 Doom',
  'Lv2 Old',
  'Lv4 Quarter',
  'Lv3 Flare',
  'Revive + Status',
  'Goblin Punch',
  'Level/Defense modifier',
  'HP Leak + Status',
  'Current MP damage',
  'Max - Current HP damage',
  'Kill Caster, Heal Raget',
  '?',
  'HP Leak + Status',
  'Flare damage + HP Leak + Status',
  'HP boost',
  'Heal HP based on current suser HP',
  '?',
  'Full Heal + Status',
  'Zombie magic',
  'Increase stats while Singing',
  'Damage creature type while Singing',
  'Unhide Monster',
  'Stalker Attack',
  'Unhide Next Page',
  'Grand Cross',
  'Chicken Knife',
  'Interceptor Rocket',
  'Targeting',
  'Pull',
  'Terminate',
  '!Control (command)',
  "? (Sandworm's Death)",
  'Status Immunity, Magic Element UP, Creature Type',
  'Strong vs. Creature type',
  'Drain HP based on current HP',
  'Brave Blade',
  'Strong Fight',
  'Wormhole',
  'Level Down',
  'Bows strong vs. Creature type',
  'Spears Strong vs. Creature type',
  'Unhide Monster',
  'Terminate',
  '?',
  '?',
  '?',
  '?',
  '?',
  '?',
  '?',
  '?',
  'Innefective',
  'No Action'
}

-- Magic Spells
TableMagicID = {
  -- SwordBlade
  "00 Sw|Fire",
  "01 Sw|Ice",
  "02 Sw|Bolt ",
  "03 Sw|Venom",
  "04 Sw|Mute ",
  "05 Sw|Sleep",
  "06 Sw|Fire2",
  "07 Sw|Ice 2",
  "08 Sw|Bolt2",
  "09 Sw|Drain",
  "0A Sw|Break",
  "0B Sw|Bio  ",
  "0C Sw|Fire3",
  "0D Sw|Ice 3",
  "0E Sw|Bolt3",
  "0F Sw|Holy ",
  "10 Sw|Flare",
  "11 Sw|Psych",
  -- White
  "12 Wh|Cure ",
  "13 Wh|Scan ",
  "14 Wh|Antdt",
  "15 Wh|Mute ",
  "16 Wh|Armor",
  "17 Wh|Size ",
  "18 Wh|Cure2",
  "19 Wh|Life ",
  "1A Wh|Charm",
  "1B Wh|Image",
  "1C Wh|Shell",
  "1D Wh|Heal ",
  "1E Wh|Cure3",
  "1F Wh|Wall ",
  "20 Wh|Bersk",
  "21 Wh|Life2",
  "22 Wh|Holy ",
  "23 Wh|Dispel",
  -- Black
  "24 Bk|Fire   ",
  "25 Bk|Ice    ",
  "26 Bk|Bolt   ",
  "27 Bk|Venom  ",
  "28 Bk|Sleep  ",
  "29 Bk|Toad   ",
  "2A Bk|Fire2  ",
  "2B Bk|Ice 2  ",
  "2C Bk|Bolt2  ",
  "2D Bk|Drain  ",
  "2E Bk|Break  ",
  "2F Bk|Bio    ",
  "30 Bk|Fire3  ",
  "31 Bk|Ice 3  ",
  "32 Bk|Bolt3  ",
  "33 Bk|Flare  ",
  "34 Bk|Doom   ",
  "35 BK|Psych  ",
  -- Dimension (Time)
  "36 Tm|Drag    ",
  "37 Tm|Slow    ",
  "38 Tm|Regen   ",
  "39 Tm|Void    ",
  "3A Tm|Haste   ",
  "3B Tm|Float   ",
  "3C Tm|Demi    ",
  "3D Tm|Stop    ",
  "3E Tm|Exit    ",
  "3F Tm|Comet   ",
  "40 Tm|Slow2   ",
  "41 Tm|Reset   ",
  "42 Tm|Qrter   ",
  "43 Tm|Hast2   ",
  "44 Tm|Old     ",
  "45 Tm|Meteo   ",
  "46 Tm|Quick   ",
  "47 Tm|Xzone   ",
  -- Summon (Spell that calls summon)
  "48 Su|Chocob ",
  "49 Su|Sylph  ",
  "4A Su|Remora ",
  "4B Su|Shiva  ",
  "4C Su|Ramuh  ",
  "4D Su|Ifrit  ",
  "4E Su|Titan  ",
  "4F Su|Golem  ",
  "50 Su|Shoat  ",
  "51 Su|Crbnkl ",
  "52 Su|Syldra ",
  "53 Su|Odin   ",
  "54 Su|Phenix ",
  "55 Su|Levia  ",
  "56 Su|Bahmut ",
  -- Songs
  "57 Sg|Power   ",
  "58 Sg|Speed   ",
  "59 Sg|Vitality",
  "5A Sg|Magic   ",
  "5B Sg|Hero    ",
  "5C Sg|Requiem ",
  "5D Sg|Love    ",
  "5E Sg|Charm   ",
  -- Summons' Action (Spell that the summon casts)
  "5F SA|Chocobo Kick              ",
  "60 SA|Whispering Wind           ",
  "61 SA|Latch On                  ",
  "62 SA|Diamond Dust              ",
  "63 SA|Bolt of Judgement         ",
  "64 SA|Hellfire                  ",
  "65 SA|Rage of the Earth         ",
  "66 SA|Earth Wall                ",
  "67 SA|Demon's Eye               ",
  "68 SA|Ruby Light                ",
  "69 SA|Thunder Storm             ",
  "6A SA|True Edge                 ",
  "6B SA|Fire of Resurection (Fire)",
  "6C SA|Big Wave                  ",
  "6D SA|Mega Flare                ",
  "6E SA|Fat Chocobo               ",
  "6F SA|Gungnir                   ",
  "70 SA|Fire of Resurection (Life)",
  -- Special Item Attacks
  "71 Dragon SW -Hp Drain            ",
  "72 Dragon SW -Mp Drain            ",
  "73 Egg Chop                           ",
  "74 Harp - Silver Harp (Item Magic 5)  ",
  "75 Harp - Dream Harp (Item Magic 6)   ",
  "76 Harp - Lamia's Harp (Item Magic 7) ",
  "77 Harp - Apollo's Harp (Item Magic 8)",
  "78 Item - Fail? (Item Magic 9)        ",
  -- Dance
  "79 Dance - Mystery Waltz              ",
  "7A Dance - Jitterbug Duet             ",
  "7B Dance - Tempting Tango             ",
  -- Command (I don't know what this is)
  "7C Command - Magic Barrier            ",
  "7D Command - Sword Dance              ",
  "7E Command - Ice Aura?                ",
  "7F Command - Entangle (Whip Magic)    ",
  -- Monster Actions
  "80 Monster Attack",
  "81 Monster Specialty",
  -- Blue
  "82 Bu|Condemn",
  "83 Bu|Roulette",
  "84 Bu|AquaRake",
  "85 Bu|L5 Doom",
  "86 Bu|L4 Qrter",
  "87 Bu|L2 Old",
  "88 Bu|L3 Flare",
  "89 Bu|FrogSong",
  "8A Bu|TinySong",
  "8B Bu|Flash",
  "8C Bu|Time Slip",
  "8D Bu|MoonFlut",
  "8E Bu|DethClaw",
  "8F Bu|Aero",
  "90 Bu|Aero 2",
  "91 Bu|Aero 3",
  "92 Bu|Emission",
  "93 Bu|GblinPnch",
  "94 Bu|DrkShock",
  "95 Bu|GuardOff",
  "96 Bu|Fusion",
  "97 Bu|MindBlst",
  "98 Bu|Vampire",
  "99 Bu|Hammer",
  "9A Bu|MgthyGrd",
  "9B Bu|Exploder",
  "9C Bu|????",
  "9D Bu|Blowfish",
  "9E Bu|WhiteWind",
  "9F Bu|Missile",
  -- Monster "Magic"
  "A0 EM|Kurururu",
  "A1 EM|Level Down",
  "A2 EM|Escape",
  "A3 EM|Stalker Attack",
  "A4 EM|Byblos Attack",
  "A5 EM|No Clue",
  "A6 EM|Grand Cross",
  "A7 EM|Delta Attack",
  "A8 EM|Interceptor Rocket",
  "A9 EM|Barrier Change",
  "AA EM|Nothing",
  "AB EM|Wind Slash",
  "AC EM|No-Damage Magic",
  "AD EM|Targeting",
  "AE EM|Gravity 100",
  "AF EM|Darkness",
  "B0 EM|Reaper's Sword",
  "B1 EM|Punishment",
  "B2 EM|Blaster",
  "B3 EM|Beak",
  "B4 EM|Hug",
  "B5 EM|Spore",
  "B6 EM|Poison Breath",
  "B7 EM|Dance of the Dead",
  "B8 EM|Zombie Powder",
  "B9 EM|Zombie Breath",
  "BA EM|Spirit",
  "BB EM|Allure",
  "BC EM|Entangle",
  "BD EM|Rainbow Wind",
  "BE EM|Strange Dance",
  "BF EM|Electromagn Field",
  "C0 EM|White Hole",
  "C1 EM|Needle",
  "C2 EM|Maelstrom",
  "C3 EM|Bone",
  "C4 EM|Tailscrew",
  "C5 EM|Stomach Acid",
  "C6 EM|Rocket Punch",
  "C7 EM|Mustard Bomb",
  "C8 EM|Almagest",
  "C9 EM|Quicksand",
  "CA EM|Atomic Ray",
  "CB EM|Mini Blaze",
  "CC EM|Snowstorm",
  "CD EM|Blaze",
  "CE EM|Electric Shock",
  "CF EM|Earth Shaker",
  "D0 EM|True Edge",
  "D1 EM|Tidal Wave",
  "D2 EM|Mega Flare",
  "D3 EM|Sonic Wave",
  "D4 EM|Thread",
  "D5 EM|Mucus",
  "D6 EM|Quake",
  "D7 EM|Strong Fight",
  "D8 EM|Medicine",
  "D9 EM|Image",
  "DA EM|Breath Wing",
  "DB EM|Flame",
  "DC EM|Thunder",
  "DD EM|Surge Beam",
  "DE EM|Fight",
  "DF EM|Remedy",
  "E0 EM|Valiant Attack",
  "E1 EM|Giga Flare",
  "E2 EM|Circle",
  "E3 EM|Wormhole",
  "E4 EM|Possess",
  "E5 EM|Dynamo",
  "E6 EM|Magnet",
  "E7 EM|Reverse Polarity",
  "E8 EM|Jump",
  "E9 EM|X-Zone",
  "EA EM|Hurricane",
  "EB EM|Demon's Eye",
  "EC EM|Pull",
  "ED EM|(6A) Invincibility? ((Sandworm) does it when he dies)",
  "EE EM|Unhide Monster",
  "EF EM|Terminate",
}

-- Abilities/Commands
TableAbilityID = {
  '00 Nothing',
  '01 Other',
  '02 Item',
  '03 Row',
  '04 Def.',
  '05 Fight',
  '06 Guard',
  '07 Kick',
  '08 BuildUp',
  '09 Mantra',
  '0A Escape',
  '0B Steal',
  '0C Capture',
  '0D Jump',
  '0E DrgnSwd',
  '0F Smoke',
  '10 Image',
  '11 Throw',
  '12 SwdSlap',
  '13 GilToss',
  '14 Slash',
  '15 Animals',
  '16 Aim',
  '17 X-Fight',
  '18 Conjure',
  '19 Observe',
  '1A Analyze',
  '1B Tame',
  '1C Control',
  '1D Catch',
  '1E Release',
  '1F Combine',
  '20 Drink',
  '21 Pray',
  '22 Revive',
  '23 Terrain',
  '24 (Nothing)',
  '25 Hide',
  '26 Show',
  '27 (MgcSwrd ?)',
  '28 Sing',
  '29 Flirt',
  '2A Dance',
  '2B Mimic',
  '2C MgcSwrd (Lv1)',
  '2D MgcSwrd (Lv2)',
  '2E MgcSwrd (Lv3)',
  '2F MgcSwrd (Lv4)',
  '30 MgcSwrd (Lv5)',
  '31 MgcSwrd (Lv6)',
  '32 White (Lv1)',
  '33 White (Lv2)',
  '34 White (Lv3)',
  '35 White (Lv4)',
  '36 White (Lv5)',
  '37 White (Lv6)',
  '38 Black (Lv1)',
  '39 Black (Lv2)',
  '3A Black (Lv3)',
  '3B Black (Lv4)',
  '3C Black (Lv5)',
  '3D Black (Lv6)',
  '3E Dimen (Lv1)',
  '3F Dimen (Lv2)',
  '40 Dimen (Lv3)',
  '41 Dimen (Lv4)',
  '42 Dimen (Lv5)',
  '43 Dimen (Lv6)',
  '44 Summon (Lv1)',
  '45 Summon (Lv2)',
  '46 Summon (Lv3)',
  '47 Summon (Lv4)',
  '48 Summon (Lv5)',
  '49 Red (Lv1)',
  '4A Red (Lv2)',
  '4B Red (Lv3)',
  '4C X-Magic',
  '4D Blue',
  '4E (Double damage)',
  '4F (Jump hit)',
  '50 (Jump miss)',
  '51 (Throbbing)',
  '52 (Jump)',
  '53 (AirBlade effect)',
  '54 (show final stats)',
  '55 (dual attack)',
  '56 (Earthquake effect)',
  '57 (Nothing)',
  '58 (Nothing)',
  '59 (Steal)',
  '5A (Row)',
  '5B (Nightingale)',
  '5C (battle stance)',
  '5D (Mysidian Rabbit)',
  '5E (Buildup)',
  '5F (Nothing)',
  '60 (Nothing)',
  '61 (Nothing)',
  '62 (Nothing)',
  '63 (Nothing)',
  '64 (Nothing)',
  '65 (Nothing)',
  '66 (Nothing)',
  '67 (Nothing)',
  '68 (Nothing)',
  '69 (Nothing)',
  '6A (Nothing)',
  '6B (Nothing)',
  '6C (Nothing)',
  '6D (Nothing)',
  '6E (Nothing)',
  '6F (Nothing)',
  '70 (Nothing)',
  '71 (Nothing)',
  '72 (Nothing)',
  '73 (Nothing)',
  '74 (Nothing)',
  '75 (Nothing)',
  '76 (Nothing)',
  '77 (Nothing)',
  '78 (Nothing)',
  '79 (Nothing)',
  '7A (Nothing)',
  '7B (Nothing)',
  '7C (Nothing)',
  '7D (Nothing)',
  '7E (Nothing)',
  '7F (Nothing)',
}

-- Passive/Support abilites
TableSupportID = {
  '80 Equip Shields',
  '81 Equip Armor',
  '82 Equip Ribbons',
  '83 Equip Swords',
  '84 Equip Spears',
  '85 Equip Katanas',
  '86 Equip Axes',
  '87 Equip Bows',
  '88 Equip Whips',
  '89 Equip Harps',
  '8A Agility Up',
  '8B HP Up 10%',
  '8C HP Up 20%',
  '8D HP Up 30%',
  '8E MP Up 10%',
  '8F MP Up 30%',
  '90 Brawl',
  '91 Double Grip',
  '92 2-Handed Grip',
  '93 Medicine',
  '94 Cover',
  '95 Counter',
  '96 Evade',
  '97 Learning',
  '98 Barrier',
  '99 Berserk',
  '9A Caution',
  '9B Alert',
  '9C See Passages',
  '9D Damage Floor',
  '9E See Pitfalls',
  '9F Equip Rods',
  'A0 Dash',
}
TableJobLevel = {
  ' ',
  ' Other',
  '!Item',
  ' Row',
  ' Def.',
  '!Fight',
  '!Guard',
  '!Kick',
  '!BuildUp',
  '!Mantra',
  '!Escape',
  '!Steal',
  '!Capture',
  '!Jump',
  '!DrgnSwd',
  '!Smoke',
  '!Image',
  '!Throw',
  '!SwdSlap',
  '!GilToss',
  '!Slash',
  '!Animals',
  '!Aim',
  '!X-Fight',
  '!Conjure',
  '!Observe',
  '!Analyze',
  '!Tame',
  '!Control',
  '!Catch',
  '!Release',
  '!Combine',
  '!Drink',
  '!Pray',
  '!Revive',
  '!Terrain',
  '(Nothing)',
  '!Hide',
  '!Show',
  '(MgcSwrd ?)',
  '!Sing',
  '!Flirt',
  '!Dance',
  '!Mimic',
  '!MgcSwrd (Lv1)',
  '!MgcSwrd (Lv2)',
  '!MgcSwrd (Lv3)',
  '!MgcSwrd (Lv4)',
  '!MgcSwrd (Lv5)',
  '!MgcSwrd (Lv6)',
  '!White (Lv1)',
  '!White (Lv2)',
  '!White (Lv3)',
  '!White (Lv4)',
  '!White (Lv5)',
  '!White (Lv6)',
  '!Black (Lv1)',
  '!Black (Lv2)',
  '!Black (Lv3)',
  '!Black (Lv4)',
  '!Black (Lv5)',
  '!Black (Lv6)',
  '!Dimen (Lv1)',
  '!Dimen (Lv2)',
  '!Dimen (Lv3)',
  '!Dimen (Lv4)',
  '!Dimen (Lv5)',
  '!Dimen (Lv6)',
  '!Summon (Lv1)',
  '!Summon (Lv2)',
  '!Summon (Lv3)',
  '!Summon (Lv4)',
  '!Summon (Lv5)',
  '!Red (Lv1)',
  '!Red (Lv2)',
  '!Red (Lv3)',
  '!X-Magic',
  '!Blue',
  '(Double damage)',
  '(Jump hit)',
  '(Jump miss)',
  '(Throbbing)',
  '(Jump)',
  '(AirBlade effect)',
  '(show final stats)',
  '(dual attack)',
  '(Earthquake effect)',
  '(Nothing)',
  '(Nothing)',
  '(Steal)',
  '(Row)',
  '(Nightingale)',
  '(battle stance)',
  '(Mysidian Rabbit)',
  '(Buildup)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  '(Nothing)',
  ' Equip Shields',
  ' Equip Armor',
  ' Equip Ribbons',
  ' Equip Swords',
  ' Equip Spears',
  ' Equip Katanas',
  ' Equip Axes',
  ' Equip Bows',
  ' Equip Whips',
  ' Equip Harps',
  ' Agility Up',
  ' HP Up 10%',
  ' HP Up 20%',
  ' HP Up 30%',
  ' MP Up 10%',
  ' MP Up 30%',
  ' Brawl',
  ' Double Grip',
  ' 2-Handed Grip',
  ' Medicine',
  ' Cover',
  ' Counter',
  ' Evade',
  ' Learning',
  ' Barrier',
  ' Berserk',
  ' Caution',
  ' Alert',
  ' See Passages',
  ' Damage Floor',
  ' See Pitfalls',
  ' Equip Rods',
  ' Dash',
}
-- Passive Job Properties
TablePassive1 = {
  'Passages',
  'Pitfalls',
  'DmgFloors',
  'Dash',
  'Learning',
  'Barrier',
  'Evade',
  'Counter',
}
TablePassive2 = {
  '2-Handed',
  'Preempt',
  'Caution',
  'Berserk',
  'Medicine+',
  'Double-Grip',
  'Brawl',
  'Cover',
}

TableTargeting = {
  '',
  '',
  'Roulette',
  'Target:Enemy',
  'Target-Selectable',
  'Side-Selectable',
  'All Targets',
  'Multi-target optional'
}
-- All Equipment types
TableEquipmentType = {
  'Nothing',
  'Common',
  'Knife',
  'Ninja Sword',
  'Sword',
  'Knight Sword',
  'Spear',
  'Axe',
  'Hammer',
  'Katana',
  'Rod',
  'Staff',
  'Flail',
  'Bow',
  'Harp',
  'Whip',
  'Bell',
  'Shield',
  'Heavy Helmet',
  'Light Helmet',
  'Mage Hat',
  'Dancer Gear',
  'Heavy Armor',
  'Light Armor',
  'Mage Robe',
  'Glove',
  'Ring',
  'Accessory',
  'Thief Gear',
  'Chemist Gear',
  'Exotic Weapon'
}
-- Quick Dbl Grip table (easier than sorting the bits)
TableDoubleGrip = {
  '2-Hand OK',
  '2-Hand Only',
  '2-Hand Only',
  ''
}
-- Equipment Stat Bonus
TableStatBonus = {
  'Mag',
  'Vit',
  'Agi',
  'Str'
}
-- Equipment Stat Bonus Value
TableStatValue = { {'+1', '  '},
  {'+2', '  '},
  {'+3', '  '},
  {'+1', '-1'},
  {'  ', '-1'},
  {'+5', '-5'},
  {'+0', '-5'},
  {'+5', '  '}
}

-- Weapon Special Properties
TableWeaponProperty = {
  'Wonder Rod',
  'Ability Attack',
  'Magic Sword OK',
  'Action on Hit',
  '',
  'First Strike',
  'Knife Parry',
  'Sword Parry'
}
-- Armor Special Properties
TableArmorProperty = {
  'Catch +',
  'Undead',
  'Dance +',
  'MP Half',
  'Steal +',
  'Brawl +',
  'Physical Dodge',
  'Magical Block'
}
-- Armor Equip Slots
TableEquipSlot = {
  'Accessory',
  'Body',
  'Head',
  'Shield'
}
-- Characters
TableCharacter = {
  'Bartz',
  'Lenna',
  'Galuf',
  'Faris',
  'Krile',
  '',
  '',
  ''
}
-- Jobs
TableJob = {
  'Knight',
  'Monk',
  'Thief',
  'Dragoon',
  'Ninja',
  'Samurai',
  'Berserker',
  'Ranger',
  'Mystic Knight',
  'White Mage',
  'Black Mage',
  'Time Mage',
  'Summoner',
  'Blue Mage',
  'Red Mage',
  'Beastmaster',
  'Chemist',
  'Geomancer',
  'Bard',
  'Dancer',
  'Mimic',
  'Freelancer'
}
-- Battle Backgrounds/Arena
TableBattleground = {
  'Grasslands',
  'Forest',
  'Desert',
  'Swamp',
  'Beach',
  'Indoor Ghost Ship',
  'Cave',
  'Waterfall Cave',
  'Castle',
  'Outdoor Castle',
  'Castle 2',
  'Castle 3',
  'Outdoor Castle 2',
  'Library',
  'Indoor Ship',
  'Forest 2',
  'Plain 2',
  'Castle 4',
  'Pier',
  'Tree Root',
  'Castle 5',
  'Outdoor Ship',
  'Steel Floor',
  'Crystal Floor',
  'Indoor Ruins',
  'Outdoor Ghost Ship',
  'Castle in Fire',
  'Wall',
  'Void',
  'Underwater Castle',
  'Desert 2',
  'Distorted Space',
  'Outdoor Castle 3',
  'Wet Plains'
}

-- Enemy Names
TableEnemy = {
  'Goblin',
  'Killer Bee',
  'Nut Eater',
  'Stray Cat',
  'Steel Bat',
  'Dearo',
  'Stroper',
  'Black Goblin',
  'White Snake',
  'Mold Wind',
  'ManiWizard',
  'Magic Pot',
  'Sucker',
  'Octoraken',
  'Gatlings',
  'Bighorn',
  'Tatu',
  'Bander S.',
  'Galura',
  'Skeleton',
  'Carcurser',
  'UndeadRusk',
  'PsychoHead',
  'RockGarter',
  'Gala Cat',
  'Cockatrice',
  'Blocks',
  'Elf Toad',
  'IceSoldier',
  'RikaldMage',
  'Wyvern',
  'Padosule',
  'Byblos',
  'Aegil',
  'Zuu',
  'Wild Nack',
  'GrassTurtle',
  'Silent Bee',
  'Mithril Drgn',
  'Ramuh',
  'Crew Dust',
  'Poltergeist',
  'Motor Trap',
  'Defeater',
  'Garkimasra',
  'Sergeant',
  'Sorcerer',
  'Karnak',
  'Gigas',
  'Page 32',
  'Page 64',
  'Page 128',
  'Page 256',
  'Ifrit',
  'Bomb',
  'TwinLizard',
  'BioSoldier',
  'Crescent',
  'BlackFlame',
  'StoneGolem',
  'MiniDragon',
  'Prototype',
  'D.Chimera',
  'Sand Porky',
  'Sand Killer',
  'Sand Bear',
  'Ra Mage',
  'LonkaKnght',
  'StonedMask',
  'Whirl Demon',
  'Lamia',
  'ArchaeToad',
  'Hyudora',
  'Hydra',
  'Water Buzz',
  'Torrent',
  'Rock Brain',
  'Tarantula',
  'Jail Bear',
  'Lunenta',
  'Dilure',
  'Faery Orc',
  'Devourer',
  'Mandrake',
  'Kuzar',
  'Cactus',
  'Sand Crawl',
  'ShieldDrgn',
  'Blood Slime',
  'Acrophese',
  'MooglEater',
  'Lopros',
  'Skull Eater',
  'Aquathone',
  'Weresnake',
  'Conago',
  'Ridicule',
  'Andagranda',
  'Drippy',
  'Likaon',
  'BoneDragon',
  'Sting Eagle',
  'ZombieDrgn',
  'Golem',
  'Neon',
  'Magnetes',
  'Wall Knight',
  'Traveler',
  'Tricker',
  'Gravido',
  'Ziggurat',
  'Cure Beast',
  'Land Turtle',
  'Bold Mani',
  'Shoat',
  'MiniMage',
  'GajraGajri',
  'Mammon',
  'Imp',
  'Wyrm',
  'Twin Lizard',
  'Blind Wolf',
  'Arage',
  'Wall Mage',
  'Magic Drgn',
  'DarkWizard',
  'AdamaGolem',
  'BalderKuar',
  'Motodrive',
  'BlueDragon',
  'Red Dragon',
  'Yellow Drgn',
  'Sleepy',
  'Treeman',
  'Hedgehog',
  'Python',
  'Shadow',
  'Elm Gigas',
  'Pao',
  'Radiator',
  'Metamorpha',
  'Unknown',
  'Desertpede',
  'Barette',
  'Sekmet',
  'BlandLamia',
  'Pyra Layer',
  'Nile',
  'Archaesaur',
  'ZephyrZone',
  'ExdethSoul',
  'Slug',
  'GloomWidow',
  'Mukare',
  'Ixecrator',
  'Owazoral',
  'ShdwDancer',
  'Cursed one',
  'Slownin',
  'TinyMage',
  'Dim Master',
  'Bone Dragon',
  'Flare',
  'DuelKnight',
  'Ion',
  'Berserker',
  'Zombie Dragon',
  'Druid',
  'Iron Dress',
  'Statue',
  'Blizzard',
  'Isteritos',
  'Spizner',
  'Unknown',
  'Unknown',
  'Unknown',
  'Unknown',
  'Mercury Bat',
  'Coral',
  'Tonberi',
  'Gel Water',
  'Fall Guard',
  'Alcumia',
  'Red Dragon (Alcumia)',
  'Hydra (Alcumia)',
  'BoneDragon (Alcumia)',
  'Grenade',
  'Sword Dancer',
  'Bardandels',
  'Doom Dealer',
  'Anku Heggu',
  'Ammona',
  'Land Crawl',
  'Chamcubia',
  'Bella Donna',
  'Cherie',
  'White Flame',
  'MossFungus',
  'Orcat',
  'Iron Gigas',
  'Death Claw',
  'K.Behemoth',
  'Fanfarerro',
  'Necromancr',
  'Ninja',
  'Great Drgn',
  'AvisDragon',
  'Gorchimera',
  'LevelCheck',
  'Mind Mage',
  'Fury',
  'Thing',
  'Mover',
  'CrysDragon',
  'Achelone',
  'Bodyguard',
  'Gilgamesh (Void)',
  'Sahagin',
  'Th.Anemone',
  'Sea Avis',
  'Corvette',
  'Armon',
  'SeaScorpio',
  'Silvune',
  'Gel Fish',
  'Giant Bird',
  'Sea Devil',
  'Stingray',
  '???? (Golem)',
  'Golem',
  'Chimera',
  'Shiva (Metamorpha)',
  'Ifrit (Metamorpha)',
  'Ramuh (Metamorpha)',
  'Gala Cat (Metamorpha)',
  'Wyvern (Metamorpha)',
  'Elf Toad (Metamorpha)',
  'Crew Dust (Metamorpha)',
  'Whirl Demon (Metamorpha)',
  'ZombieDrgn (Metamorpha)',
  'D.Chimera (Zephyr Zone)',
  'AdamaGolem (Zephyr Zone)',
  'Ziggurat (Zephyr Zone)',
  'LonkaKnght (Zephyr Zone)',
  'BioSoldier (Zephyr Zone)',
  'Lunenta (Zephyr Zone)',
  'Tote Avis',
  'Belfegor',
  'Imp (Exdeath Castle)',
  'Owazoral (Exdeath Castle)',
  'Garkimasra (Exdeath Castle)',
  'Gabbledegak',
  'Gil Turtle',
  'Omega',
  'Big Boss',
  'None',
  'WingRaptor (1st Form)',
  'WingRaptor (2nd Form)',
  'Karlaboss',
  'Twin Tania (2nd form)',
  'Siren (1st Form)',
  'Siren (2nd Form)',
  'Forza',
  'Magisa',
  'Galura',
  'LiquiFlame (Human)',
  'LiquiFlame (Hand)',
  'LiquiFlame (Whirlwind)',
  'Commander',
  'Sandworm',
  'Hole (Sandworm)',
  '____ (Sandworm)',
  'AdamanTiMi',
  'FlameGun',
  'Rocket',
  'Exdeath (Final Battle)',
  'Sol Cannon',
  'Archaeavis (1st Form)',
  'Archaeavis (2nd Form)',
  'Archaeavis (3rd Form)',
  'Archaeavis (4th Form)',
  'Archaeavis (Undead)',
  'Chim.Brain',
  'Titan',
  'Puroboros',
  'Abductor (Butz Battle)',
  'Gilgamesh (Dungeon)',
  'Fishman',
  'FlyingKillr',
  "Lil'Chariot",
  'NeoGalura',
  'Gilgamesh (Bridge)',
  'Tyrasaurus',
  'Shiva',
  'Abductor (Val Castle)',
  'HiryuuPlant',
  'HiryuuFlowr (1)',
  'HiryuuFlowr (2)',
  'HiryuuFlowr (3)',
  'HiryuuFlowr (4)',
  'HiryuuFlowr (5)',
  "Gilgamesh (Zeza's Fleet)",
  'Enkidou',
  'Atmos',
  '(Seal Guardian - Fire)',
  '(Seal Guardian - Earth)',
  '(Seal Guardian - Water)',
  '(Seal Guardian - Air)',
  'Carbunkle ()',
  'Merugene (*Demo)',
  'Gilgamesh (Morphed - Exdeath Castle)',
  'Exdeath (Exdeath Castle)',
  'Antlion',
  'Mummy',
  'Aspis',
  'MachinHead',
  'Merugene (Form 1)',
  'Merugene (Form 2)',
  'Merugene (Form 3)',
  'Merugene (Form 4)',
  'Odin',
  'Gargoyle',
  'Triton',
  'Neregeid',
  'Phobos',
  'Omniscient',
  'Minotauros',
  'Leviathan',
  'Stalker',
  'Gogo',
  'Bahamut',
  'Jura Avis',
  'Halicarnaso',
  'Exdeath (vs Galuf)',
  'NeoExdeath (Fake 1)',
  'NeoExdeath (Fake 2)',
  'Goblin (Butz Fight)',
  'Iron Claw',
  'Sergeant ()',
  'Karnak ()',
  'Crayclaw',
  'NeoGoblin',
  'Calofisteri',
  'Apocalypse',
  'Catastroph',
  'Necrofobia',
  'Twin Tania (1st form)',
  'Launcher',
  'Launcher',
  'Gigamesh (Exdeath Castle)',
  'Carbunkle ()',
  'GrandMummy',
  'Apanda',
  'Alte Roite',
  'Invisible',
  'Abductor (Exdeath Castle)',
  'BandelKuar (Phoenix Tower)',
  'LiquiFlame (Phoenix Tower)',
  'Kuzar (Phoenix Tower)',
  'Sol Cannon (Phoenix Tower)',
  'Pantera',
  'Shinryuu',
  'Barrier',
  'Neo Exdeath (Part 1)',
  'Neo Exdeath (Part 2)',
  'Neo Exdeath (Part 3)',
  'Neo Exdeath (Part 4)',
  'Gilgamesh (Necrofobia)',
}

TableItemID = { "Nothing           ",
  "Empty             ",
  "Knife             ",
  "Dagger            ",
  "Mythril Knife     ",
  "Kunai             ",
  "Mage Masher       ",
  "Guardian          ",
  "Kodachi           ",
  "Orialicn          ",
  "Air Lance         ",
  "Assassin          ",
  "Hardened (Sasuke) ",
  "Broadsword        ",
  "RegalCut          ",
  "Mythril Sword     ",
  "Coral Sword       ",
  "Ancient Sword     ",
  "Epee Sword        ",
  "Slumber Sword     ",
  "Defender Sword    ",
  "Excalibur         ",
  "Ragnarok          ",
  "Javelin           ",
  "Spear             ",
  "Mythril Spear     ",
  "Trident           ",
  "Wind Spear        ",
  "Partisan          ",
  "Gungnir           ",
  "DblLance          ",
  "Holy Lance        ",
  "Dragoon Lance     ",
  "Battle Axe        ",
  "Mythril Hammer    ",
  "Ogre Killer       ",
  "War Hammer        ",
  "Venom Axe         ",
  "Earth Hammer      ",
  "Rune Axe          ",
  "Thor Hammer       ",
  "Katana            ",
  "Air Blade         ",
  "Kotetsu           ",
  "Bizen             ",
  "Forged            ",
  "Murasume          ",
  "Masamune          ",
  "Tempest           ",
  "Rod               ",
  "Fire Rod          ",
  "Ice Rod           ",
  "Thunder Rod       ",
  "Venom Rod         ",
  "Lillith Rod       ",
  "Wizard Rod        ",
  "Staff             ",
  "Mythril Staff     ",
  "Power Staff       ",
  "Healing Staff     ",
  "Staff of Light    ",
  "Sage's Staff      ",
  "Judgement Staff   ",
  "Fire Bow          ",
  "Ice Bow           ",
  "Thunder Bow       ",
  "Darkness Bow      ",
  "Killer Bow        ",
  "Elven Bow         ",
  "Yoichi Bow        ",
  "Artemis Bow       ",
  "Silver Harp       ",
  "Dream Harp        ",
  "Lamia's Harp      ",
  "Apollo's Harp     ",
  "Whip              ",
  "Chain Whip        ",
  "Thunder Whip      ",
  "Flame Whip        ",
  "Dragon's Whisker  ",
  "Giyaman           ",
  "Earth Bell        ",
  "Rune Chime        ",
  "Tinkerbell        ",
  "Sabre (*Dummy)    ",
  "Drain Sword       ",
  "RuneEdge          ",
  "Flametongue       ",
  "IceBrand          ",
  "Full Moon         ",
  "Shuriken          ",
  "Pinwheel          ",
  "Excailbur         ",
  "BeastKiller       ",
  "Flail             ",
  "Morning Star      ",
  "Wonder Wand       ",
  "Brave Blade       ",
  "Soot              ",
  "Chicken Knife     ",
  "RisingSun         ",
  "Silver Bow        ",
  "Gale Bow          ",
  "AntiMagic Bow     ",
  "Avis Killer       ",
  "DoomCut           ",
  "Giant's Axe       ",
  "ManEater          ",
  "Thief Knife       ",
  "Dancing Dagger    ",
  "Enhancer          ",
  "L. Hand           ",
  "R. Hand           ",
  "Item0000 (*Dummy) ",
  "Item0000 (*Dummy) ",
  "Item0000 (*Dummy) ",
  "Item0000 (*Dummy) ",
  "Item0000 (*Dummy) ",
  "Item0000 (*Dummy) ",
  "Item0000 (*Dummy) ",
  "Item0000 (*Dummy) ",
  "Item0000 (*Dummy) ",
  "Item0000 (*Dummy) ",
  "Item0000 (*Dummy) ",
  "Item0000 (*Dummy) ",
  "Item0000 (*Dummy) ",
  "Item0000 (*Dummy) ",
  "Item0000 (*Dummy) ",
  "                  ",
  "Leather Shield    ",
  "Bronze Shield     ",
  "Iron Shield       ",
  "Mythril Shield    ",
  "Golden Shield     ",
  "Aegis Shield      ",
  "Diamond Shield    ",
  "Crystal Shield    ",
  "Leather Cap       ",
  "Bronze Helm       ",
  "Iron Helm         ",
  "Mythril Helm      ",
  "Golden Helm       ",
  "Diamond Helm      ",
  "Crystal Helm      ",
  "Plumed Hat        ",
  "Tricorn Hat       ",
  "Magus             ",
  "Circlet           ",
  "Gold Hairpin      ",
  "Ribbon            ",
  "Bandana           ",
  "GrnBeret          ",
  "DarkHood          ",
  "Lamia's Tiara     ",
  "Leather Armor     ",
  "Bronze Armor      ",
  "Iron Armor        ",
  "Mythril Armor     ",
  "Golden Armor      ",
  "Diamond Armor     ",
  "Crystal Armor     ",
  "CopperPlt         ",
  "Training Suit     ",
  "Silver Plate      ",
  "Stealth Suit      ",
  "DiamndPlt         ",
  "DarkSuit          ",
  "Cotton Robe       ",
  "Silk robe         ",
  "Gaia Gear         ",
  "Bard's Surplice   ",
  "Lumina Robe       ",
  "Black Robe        ",
  "White Robe        ",
  "Mirage Vest       ",
  "Guard Ring        ",
  "Thief's Glove     ",
  "Giant's Gloves    ",
  "Elf Cape          ",
  "Cursed Ring       ",
  "Glasses           ",
  "Running Shoes     ",
  "Mythril Glove     ",
  "Silver Armlet     ",
  "Diamond Armlet    ",
  "Strength          ",
  "Power Wrist       ",
  "Angel Gwn         ",
  "Angel Ring        ",
  "Flame ring        ",
  "Coral ring        ",
  "Bone Mail         ",
  "Leather Shoes     ",
  "Kaiser Knuckles   ",
  "Gauntlets         ",
  "Tiger Mask        ",
  "Flame Shield      ",
  "CornaJar          ",
  "Genji Shield      ",
  "Genji Helm        ",
  "Genji Armor       ",
  "Genji Gloves      ",
  "Wall Ring         ",
  "Coronet           ",
  "Thornlet          ",
  "Ice Shield        ",
  "Cursed Shield     ",
  "Rainbow Dress     ",
  "Red Shoes         ",
  "Item0000 (*Dummy) ",
  "Item0000 (*Dummy) ",
  "Item0000 (*Dummy) ",
  "Item0000 (*Dummy) ",
  "Item0000 (*Dummy) ",
  "Item0000 (*Dummy) ",
  "Item0000 (*Dummy) ",
  "Item0000 (*Dummy) ",
  "Item0000 (*Dummy) ",
  "Item0000 (*Dummy) ",
  "Item0000 (*Dummy) ",
  "Item0000 (*Dummy) ",
  "Item0000 (*Dummy) ",
  "Item0000 (*Dummy) ",
  "Item0000 (*Dummy) ",
  "Potion            ",
  "Hi-Potion         ",
  "Ether             ",
  "Elixir            ",
  "Phoenix Down      ",
  "Maiden's Kiss     ",
  "Revivify          ",
  "TurtleShell       ",
  "Antidote          ",
  "Eyedrop           ",
  "DragonFang        ",
  "DarkMatter        ",
  "Soft              ",
  "LuckMallet        ",
  "Dummy (*Dummy)    ",
  "MagicLamp         ",
  "Tent              ",
  "Cabin             ",
  "Giant Drink       ",
  "Power Drink       ",
  "Speed Drink       ",
  "Protect Drink     ",
  "Hero Drink        ",
  "DrgnCrest         ",
  "OmegaMedl         ",
  "Ramuh             ",
  "Shoat             ",
  "Golem             ",
  "Flame Tech        ",
  "Water Tech        ",
  "Thunder Tech      ",
  "FF (*Dummy)       ",

}
